In [1]:
#importing the dependencies 
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [2]:
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier


In [3]:
#loding the dataset
data=pd.read_csv('../dataset/heart.csv')

In [4]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
#splitting the data into x and y
x=data.drop(columns='target',axis=1)
y=data.target

In [6]:
print(x)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [7]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


In [8]:
#converting the Values of x and y in the form of numpy arrays 
X=np.asarray(x)
Y=np.asarray(y)

In [9]:
print(X)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]


In [10]:
print(Y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


## Model selection 

comparing the model with default hyperparameter value using cross validation 

In [11]:
#list of models 
models=[LogisticRegression(max_iter=10000),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [12]:
def cross_val_comparision():
    for model in models:
        cv_score=cross_val_score(model,X,Y,cv=5)
        mean_accuracy=sum(cv_score)/len(cv_score)
        print(f"the cross validation score of {model} is ={cv_score}")
        print(f"the accuracy score of the {model} is:{mean_accuracy*100:.2f}%")
        print("-------------------------------------------------------------")

In [13]:
cross_val_comparision()

the cross validation score of LogisticRegression(max_iter=10000) is =[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
the accuracy score of the LogisticRegression(max_iter=10000) is:82.83%
-------------------------------------------------------------
the cross validation score of SVC(kernel='linear') is =[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
the accuracy score of the SVC(kernel='linear') is:82.83%
-------------------------------------------------------------
the cross validation score of KNeighborsClassifier() is =[0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
the accuracy score of the KNeighborsClassifier() is:64.39%
-------------------------------------------------------------
the cross validation score of RandomForestClassifier() is =[0.83606557 0.90163934 0.78688525 0.8        0.78333333]
the accuracy score of the RandomForestClassifier() is:82.16%
-------------------------------------------------------------


**Note-->** the Logistic regression has the highest accuracy among all the other three models

**Note2-->** the KNeighborclassifier has the lowest accurcy among all of them 

## Applying the gridsearchcv

In [15]:
models1=[LogisticRegression(max_iter=10000),SVC(),KNeighborsClassifier(),RandomForestClassifier()]

In [16]:
model_hyperparameter={
    'log_hyperparameters':{
        'C':[1,5,10,20]
    },
    'svc_hyperparameters':{
        'kernel':['linear','poly','rbf','sigmoid'],
        'C':[1,5,10,20]
    },
    'knn_hyperparameters':{
        'n_neighbors':[3,5,10]
    },
    'rfc_hyperparameters':{
        'n_estimators':[10,20,50,100]
    }
}

In [17]:
type(model_hyperparameter)

dict

In [18]:
print(model_hyperparameter.values())

dict_values([{'C': [1, 5, 10, 20]}, {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}, {'n_neighbors': [3, 5, 10]}, {'n_estimators': [10, 20, 50, 100]}])


In [20]:
model_hyperparameter['log_hyperparameters']

{'C': [1, 5, 10, 20]}

In [23]:
model_keys=list(model_hyperparameter.keys())

In [24]:
print(model_keys)

['log_hyperparameters', 'svc_hyperparameters', 'knn_hyperparameters', 'rfc_hyperparameters']


In [25]:
model_hyperparameter[model_keys[0]]

{'C': [1, 5, 10, 20]}

## Applying the GridSeachCV

In [32]:
def Model_selection(model_list,hyperparameter_dict):
    result=[]
    i=0
    for model in model_list:
        key=model_kyes[i]
        params=hyperparameter_dict[key]
        i+=1
        print(model)
        print(params)
        print("--------------------------")
        #applying the grid seach cv
        classifier=GridSearchCV(model,params,cv=5)
        classifier.fit(X,Y)
        result.append({
            'model_used':model,
            'highest_score':classifier.best_score_*100,
            "best_parameters":classifier.best_params_
                })
    result_dataframe=pd.DataFrame(result,columns=['model_used','highest_score','best_parameters'])
    return result_dataframe
    

In [ ]:
Model_selection(models1,model_hyperparameter)

LogisticRegression(max_iter=10000)
{'C': [1, 5, 10, 20]}
--------------------------
SVC()
{'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}
--------------------------
